variables:
  var-hubnetwork-region: canadacentral
  var-hubnetwork-managementGroupId: Connectivity
  var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  var-hubnetwork-subscriptionId: 00ea15da-336c-43f5-9aa1-59cc82988560
  var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  var-logging-managementGroupId: Management
  var-logging-subscriptionId: f5ee311b-e8e2-4e78-a0e1-45c75c91b068
  deploymentRegion: canadacentral
  var-identity-managementGroupId: Identity
  var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
      "id": "98ef921c-3aac-4ec5-bc8d-10cc0c4f0430",
      "name": "Tenant Root Group",
      "children": [
        {
          "id": "pubsec",
          "name": "Canadian Public Sector Azure Landing Zones",
          "children": [
            {
              "id": "Platform",
              "name": "Platform",
              "children": [
                {
                  "id": "Management",
                  "name": "Management",
                  "children": []
                },
                {
                  "id": "Connectivity",
                  "name": "Connectivity",
                  "children": []
                },
                {
                  "id": "Identity",
                  "name": "Identity",
                  "children": []
                }
              ]
            },
            {
              "id": "LandingZones",
              "name": "LandingZones",
              "children": [
                {
                  "id": "DevTest",
                  "name": "DevTest",
                  "children": []
                },
                {
                  "id": "QA",
                  "name": "QA",
                  "children": []
                },
                {
                  "id": "Prod",
                  "name": "Prod",
                  "children": []
                }
              ]
            },
            {
              "id": "Sandbox",
              "name": "Sandbox",
              "children": []
            }
          ]
        }
      ]
    }
  var-logging-region: canadacentral
  # var-identity-configurationFileName: identity.parameters.json
  # var-identity-region: canadacentral
  # var-identity-subscriptionId: 2987c7a3-1e43-4b28-b983-ac0925e37d03

